### ISSUE TITLE
Develop GameState

### ISSUE THREAD

**Issue by ThomasKeough** [ThomasKeough/bedrock#17]
We will need a GameState object to identify if a game has ended yet. 
The GameState object should be updated every turn by the GameLoop (which also needs to be implemented).

GameState must keep track of how many of each player's Pokemon have fainted and how many turns have occurred. It must also be able to identify who will make the next move. Lastly, it needs to run a check after each turn to see if the game loop should end. This will be a check on the number of Pokemon fainted per player -- if either player has six fainted Pokemon, the game must end.

**Comment by dharhar** [comment]
implemented gamestate
